---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# mpas-and-catch

<!-- badges: start -->
<!-- badges: end -->

The goal of mpas-and-catch is to explore a regression discontinuity design around country-level catch and country-level MPA coverage

## Reproducing Results

All materials needed to reproduce our results and manuscript are contained in this repository. In order to reproduce

1. Fork the repository and clone to your machine

2. Open R and set your working directory of the cloned repository (or just use RStudio projects)

3. This project is set up with [`renv`](https://rstudio.github.io/renv/articles/renv.html) to manage package dependencies. Inside R (and with your working directory set correctly) run `renv::restore()`. This will install the correct versions of all the packages needed to replicate our results. Packages are installed in a stand-alone project library for this paper, and will not affect your installed R packages anywhere else. 
